manifest:
  defaults:
    remote: github
    revision: master

  remotes:
    - name: github
      url-base: ssh://git@github.com

  projects:
    - name: ridephysics/imulogger
      path: imulogger
      west-commands: scripts/west-commands.yml

    - name: espressif/esp-idf
      path: external/esp-idf

  self:
    path: manifest

  configs:
    zephyr:
      disabled: true
